### ISSUE TITLE
Get customer address by ID

### ISSUE THREAD

**Issue by CHH** [sphereio/commercetools-php-sdk#162]
Often I want to retrieve a customer’s address by its ID, for example to edit it in an UI. It would be great if there would be a way to do this.

There is `AddressCollection::getBy` and I tried calling `$customer->getAddresses()->getBy('id', $addressId)`, but this doesn’t work. Looks like the addresses are not indexed when the AddressCollection is created, because `indexRow` of the base Collection isn’t overridden by the AddressCollection.

**Comment by nkuehn** [comment]
Hi Christoph, it looks like you're right - there are no specific indexed fields so that you can easily access e.g. the default shipping address. But @jayS-de  will have to cross-check once he is available again. 

Would it help if the Customer provides helpers  for `getDefaultShippingAddress()` etc. that directly return the Adress Object?

**Comment by CHH** [comment]
@nkuehn:

> Would it help if the Customer provides helpers for getDefaultShippingAddress() etc. that directly return the Adress Object?

That would also be perfect.
